spring:
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/postgis
    username: testnutzer
    password: testpasswort

  jpa:
    hibernate:
      ddl-auto: create-drop

hibernate:
  dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  show_sql: true